version: '3'

services:
    php:
        build:
          context: ./
          dockerfile: ./Dockerfile
        env_file:
            - ./.env
        # Comment out these volumes in production
        volumes:
            - ./:/srv:rw
            # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
            - /srv/var/
            - /srv/var/cache/
            - /srv/var/logs/
            - /srv/var/sessions/

    nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        depends_on:
            - php
        ports:
            - "8080:80"
        volumes:
            - ./public:/srv/public:ro
