version: '3'

services:
    php:
        build:
          context: ./
          dockerfile: ./Dockerfile
        depends_on:
            - db
        env_file:
            - ./.env
        # Comment out these volumes in production
        volumes:
            - ./:/srv:rw
            # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
            - /srv/var/
            - /srv/var/cache/
            - /srv/var/logs/
            - /srv/var/sessions/

    nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        depends_on:
            - php
        ports:
            - "8080:80"
        volumes:
            - ./public:/srv/public:ro

    db:
        # In production, you may want to use a managed database service
        build:
            context: ./docker/mysql
            dockerfile: ./Dockerfile
        volumes:
            - db-data:/var/lib/mysql/data:rw
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            # - ./docker/db/data:/var/lib/postgresql/data:rw
        ports:
            - "3306:3306"

volumes:
    db-data: {}
